version: '3'
services:
  db:
    image: 'mysql:5'
    ports: 
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=CST8257
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/CST8257.sql
  web:
    build: ./server
    ports:
      - '5000:80'
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db